# https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow
name: deploy-ghpages-docsite
# github actions ternary operator: https://7tonshark.com/posts/github-actions-ternary-operator/
run-name: ${{ github.ref == 'refs/heads/main' && 'Deploy to GitHub Pages' || 'Build GitHub Pages artifact' }} by ${{ github.actor }}
on: [push]
jobs:
  # Build job
  build:
    # Specify runner + build steps
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3
        with:
          submodules: true
      # Setup .NET
      - name: Setup .NET Core SDK 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      # Install dependencies
      - name: Install dependencies
        run: dotnet restore
      # Generate docsite
      - name: Build
        run: dotnet run --project CommsRadioDocsSite/CommsRadioDocsSite.csproj
      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: CommsRadioDocsSite/output

  # Deploy job
  deploy:
    # Add a dependency on the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write
      id-token: write

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
